spring:
    datasource:
        url: jdbc:postgresql://db-companies:5432/companies-qa
        username: debuggeandoideas
        password: udemy
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
